# Generated by Django 4.1.1 on 2022-10-02 03:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("advertisements", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisement",
            name="in_favorites",
            field=models.ManyToManyField(
                related_name="favorites", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="status",
            field=models.TextField(
                choices=[
                    ("OPEN", "Открыто"),
                    ("CLOSED", "Закрыто"),
                    ("DRAFT", "Черновик"),
                ],
                default="OPEN",
            ),
        ),
    ]
