# Generated by Django 4.1 on 2022-09-21 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_alter_sensor_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='updated_at',
        ),
    ]
